### Without Bias

In [1]:
import numpy as np

def bipolar_step(y, th=0):
    return [1 if i > th else 0 if i == th else -1 for i in y]

def hebb_assoc_train(s, t):
    w = np.zeros((len(s[0]), len(t[0])))
    for r, row in enumerate(s):
        for c, col in enumerate(row):
            w[c] = [w[c, i] + col * t[r, i] for i in range(len(t[r]))]
    return w

def hebb_assoc_test(x, w):
    y = [np.dot(x, w[:, i]) for i in range(len(w[0]))]
    return bipolar_step(y)

s = [[-1, -1, -1],
    [-1, -1, 1],
    [1, 1, -1],
    [1, 1, 1]]

b = ([1],
     [1],
     [1],
     [1])

t = np.array([[-1, 1],
              [-1, 1],
              [1, -1],
              [1, -1]])
w = hebb_assoc_train(s, t)
y = hebb_assoc_test([1, 1, -1], w)
print(w)
print(y)

[[ 4. -4.]
 [ 4. -4.]
 [ 0.  0.]]
[1, -1]


### Menggunakan Bias

In [2]:
import numpy as np

def bipolar_step(y, th=0):
    return np.where(y > th, 1, np.where(y == th, 0, -1))

def hebb_assoc_train(s, t, b):
    w = np.zeros((len(s[0]), len(t[0])))
    for r, row in enumerate(s):
        for c, col in enumerate(row):
            w[c] = [w[c, i] + col * t[r, i] for i in range(len(t[r]))]
        b[r] = [b[r, i] + t[r, i] for i in range(len(t[r]))]
    return w, b

def hebb_assoc_test(x, w, b):
    y = [np.dot(x, w[:, i]) + b[i] for i in range(len(w[0]))]
    return bipolar_step(np.array(y))

s = [[-1, -1, -1],
    [-1, -1, 1],
    [1, 1, -1],
    [1, 1, 1]]

bias = np.array([[1, 1],
                 [1, 1],
                 [1, 1],
                 [1, 1]])

t = np.array([[-1, 1],
              [-1, 1],
              [1, -1],
              [1, -1]])

w, bias = hebb_assoc_train(s, t, bias)
x_test = [1, 1, -1]
y = hebb_assoc_test(x_test, w, bias)
print("Weight Matrix (w):")
print(w)
print("Updated Bias (b):")
print(bias)
print("Output (y):")
print(y)


Weight Matrix (w):
[[ 4. -4.]
 [ 4. -4.]
 [ 0.  0.]]
Updated Bias (b):
[[0 2]
 [0 2]
 [2 0]
 [2 0]]
Output (y):
[[ 1  1]
 [-1 -1]]
