---
## Hebb Rule menggunakan Hetero Associative Memory

###### (F1D020050)
---

In [1]:
# Import library
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

---
### Permasalahan

<img src="./image/problem.png" alt="image" width="400" height="150">

Buatlah desain HAM menggunkaan Delta rule!

---
Note:


Aturan Hebbian adalah prinsip dasar dalam pembelajaran sinaptik yang menyatakan bahwa koneksi sinaptik antara dua neuron diperkuat ketika keduanya aktif bersamaan. Tidak ada penggunaan "learning rate" dalam aturan Hebbian, dan perubahan bobot sinaptik terjadi secara langsung sesuai dengan aktivitas neuron prasesinaptik dan postsinaptik. Ini adalah prinsip dasar yang digunakan untuk mengekspresikan korelasi aktivitas neuron dalam proses pembelajaran, tetapi mungkin tidak cocok untuk tugas pembelajaran yang lebih kompleks yang memerlukan kontrol yang lebih halus atas pembelajaran seperti yang diberikan oleh algoritma berbasis gradien dengan learning rate.

---

In [2]:
# Input Pattern
X = np.array([[-1, -1, -1],
              [-1, -1, 1],
              [1, 1, -1],
              [1, 1, 1]])

# Bias
B = np.array([1, 1, 1, 1])

# Target Pattern
T = np.array([[-1, 1],
              [-1, 1],
              [1, -1],
              [1, -1]])

# Inisialisasi weight matrix dan bias vektor menggunakan np.zeros()
W = np.zeros((X.shape[1], T.shape[1]))
bias = np.zeros(T.shape[1])

### Bipolar Step Function

<img src="./image/bipolar.png" alt="image" width="170" height="100">
<img src="./image/rumus_bipolar.png" alt="image" width="170" height="100">


In [3]:
# Activation function bipolar
def bipolar_activation(x, threshold=0):
    return np.where(x > threshold, 1, np.where(x == threshold, 0, -1))

### Algorithm

### Algoritma Delta Rule dan Hetero Associative Memory

1) Inisialisasi semua bobot dengan nilai 0
2) Untuk setiap data latih 𝑠 dan target 𝑡, lakukan langkah 3–5
3) Set nilai aktivasi setiap neuron input:
   
   $ 𝑥_𝑖 = 𝑠_i $
4) Hitung nilai $ y_{in} $ :
   
   $ y_{j} = t_{j}$
5) Update nilai bobot:

   $ w'_{ij} = w_{ij} + x_iy_j $

In [4]:
# Hebbian learning rule menggunakan bias
def hebbian_learning(input_pattern, target_pattern, weight_matrix, bias):
    output = np.dot(input_pattern, weight_matrix) + bias
    weight_matrix += np.outer(input_pattern, target_pattern)
    bias += target_pattern
    print("Bias update ",bias)

### HAM

3) Set nilai vektor input ke neuron input
4) Karena dalam code ini akan menggunakan HAM, maka nilai y_{in} update akan diubah ke dalam mekanisme berikut:

   $ y_{in_j} = sum_{i=1}^{n} (x_iw_{i_j}) $
5) Update nilai bobot sesuai Delta Rule
6) Gunakan Activation Function dalam hal ini Bipolar

In [5]:
# Melatih hetero-associative memory menggunakan Hebbian learning
for i in range(X.shape[0]):
    hebbian_learning(X[i], T[i], W, bias)

print("\nBias yang dihasilkan:\n",bias)
print("\nNilai Weight yang dihasilkan:\n",W)

# Membuat asosiasi antara input patterns dan target patterns
def hetero_associative_memory(input_pattern, weight_matrix, bias):
    output = bipolar_activation(np.dot(input_pattern, weight_matrix) + bias)
    return output

Bias update  [-1.  1.]
Bias update  [-2.  2.]
Bias update  [-1.  1.]
Bias update  [0. 0.]

Bias yang dihasilkan:
 [0. 0.]

Nilai Weight yang dihasilkan:
 [[ 4. -4.]
 [ 4. -4.]
 [ 0.  0.]]


### Testing

Acuan:

<img src="./image/problem.png" alt="image" width="400" height="150">

#### Testing menggunakan 1 data

In [6]:
# Test hetero-associative memory
input_pattern = [1, 1, 1] # Masukkan input pattern yang ingin diuji
output_pattern = hetero_associative_memory(input_pattern, W, bias)

print("Input Pattern:", input_pattern)
print("Associated Output Pattern:", output_pattern)

Input Pattern: [1, 1, 1]
Associated Output Pattern: [ 1 -1]


#### Test Menggunakan multiple input scenario

In [7]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

# Data sebenarnya (actual)
actual_data = np.array([[-1, 1],
                        [1, -1],
                        [-1, 1],
                        [1, -1]])

# Bias
B = np.array([1, 1, 1, 1])

# Vektor input untuk pengujian
test_inputs = np.array([[-1, -1, -1],
                        [1, 1, -1],
                        [-1, -1, 1],
                        [1, 1, 1]])

from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

print("Input: \n", test_inputs)
print("\nNilai target (hasil seharusnya): \n", actual_data)

# Fungsi untuk melakukan pengujian
def perform_testing(test_inputs, actual_data, weight_matrix, bias, threshold=0):
    predicted_data = []
    
    for input_pattern in test_inputs:
        # Menggunakan Hebbian learning untuk menghitung output
        net_output = np.dot(input_pattern, weight_matrix) 
        output = bipolar_activation(net_output, threshold)
        predicted_data.append(output)
    
    # Konversi hasil prediksi ke dalam bentuk numpy array
    predicted_data = np.array(predicted_data)
    
    # Menghitung confusion matrix
    conf_matrix = confusion_matrix(actual_data.ravel(), predicted_data.ravel())
    
    # Membuat classification report
    class_report = classification_report(actual_data.ravel(), predicted_data.ravel())
    
    return conf_matrix, class_report, predicted_data

# Lakukan pengujian
confusion_matrix_result, classification_report_result, predicted_data = perform_testing(test_inputs, actual_data, W, B)

# Output Prediksi
print("\n\n======================================================\nHasil Prediksi: \n", predicted_data)

# Tampilkan hasil confusion matrix
print("\n======================================================\nConfusion Matrix:")
print(confusion_matrix_result)

# Tampilkan hasil classification report
print("\nClassification Report:")
print(classification_report_result)

Input: 
 [[-1 -1 -1]
 [ 1  1 -1]
 [-1 -1  1]
 [ 1  1  1]]

Nilai target (hasil seharusnya): 
 [[-1  1]
 [ 1 -1]
 [-1  1]
 [ 1 -1]]


Hasil Prediksi: 
 [[-1  1]
 [ 1 -1]
 [-1  1]
 [ 1 -1]]

Confusion Matrix:
[[4 0]
 [0 4]]

Classification Report:
              precision    recall  f1-score   support

          -1       1.00      1.00      1.00         4
           1       1.00      1.00      1.00         4

    accuracy                           1.00         8
   macro avg       1.00      1.00      1.00         8
weighted avg       1.00      1.00      1.00         8



In [8]:
mse = np.mean((predicted_data - actual_data) ** 2)

print("Mean Squared Error (MSE):", mse)

Mean Squared Error (MSE): 0.0
