---
### Delta Rule menggunakan Hetero Associative Memory

###### (F1D020050)
---

In [1]:
# Import library
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

---
### Permasalahan

<img src="./image/problem.png" alt="image" width="400" height="150">

Buatlah desain HAM menggunkaan Delta rule!

---

Dalam konteks Delta Rule, bias dimasukkan dalam proses pembelajaran karena bias mewakili pergeseran konstan dalam jaringan saraf, memengaruhi ambang aktivasi, dan berkontribusi pada output jaringan. Bias biasanya dianggap sebagai parameter yang serupa dengan bobot, dan disesuaikan bersamaan dengan bobot lainnya selama pelatihan untuk memungkinkan jaringan mempelajari hubungan yang sesuai antara masukan dan keluaran. Ini memastikan bahwa jaringan saraf dapat efektif beradaptasi dan mengoptimalkan proses pengambilan keputusan dengan mempertimbangkan nilai-nilai pergeseran ini dalam perhitungannya.

---

In [2]:
# Data input X dan target t
# x = [input, input, input, bias]

X = np.array([[-1, -1, -1, 1],
              [-1, -1, 1, 1],
              [1, 1, -1, 1],
              [1, 1, 1, 1]])

# Target
t = np.array([[-1, 1],
              [-1, 1],
              [1, -1],
              [1, -1]])

In [3]:
# Inisialisasi Weight Matrix W
W = np.random.rand(X.shape[1], t.shape[1])

# Learning rate (tingkat pembelajaran)
learning_rate = 0.1

# Jumlah iterasi pembelajaran
num_iterations = 100

### Bipolar Step Function

<img src="./image/bipolar.png" alt="image" width="170" height="100">
<img src="./image/rumus_bipolar.png" alt="image" width="170" height="100">


In [4]:
# Activation function bipolar
def bipolar_activation(x, threshold=0):
    if x > threshold:
        return 1
    elif x == threshold:
        return 0
    else:
        return -1

### HAM Function

In [5]:
# Fungsi untuk mengambil output berdasarkan input dengan aktivasi bipolar
def ham_bipolar(input_vector, weight_matrix):
    output = np.dot(input_vector, weight_matrix)
    return np.array([bipolar_activation(x) for x in output])

### Algoritma Delta Rule dan Hetero Associative Memory

1) Inisialisasi semua bobot dengan nilai 0
2) Untuk setiap data latih 𝑠 dan target 𝑡, lakukan langkah 3–5
3) Set nilai aktivasi setiap neuron input:
   
   $ 𝑥_𝑖 = 𝑠_i $
4) Hitung nilai $ y_{in} $ :
   
   $ y_{in} = sum_{i=1}^{n} (x_iw_i) $
5) Update nilai bobot:

   $  \Delta w_i = a(t-y_{in}) *xi $

   $ w_i(new) = w_i + \Delta w_i $

### HAM

3) Set nilai vektor input ke neuron input
4) Karena dalam code ini akan menggunakan HAM, maka nilai y_{in} update akan diubah ke dalam mekanisme berikut:

   $ y_{in_j} = sum_{i=1}^{n} (x_iw_{i_j}) $
5) Update nilai bobot sesuai Delta Rule
6) Gunakan Activation Function dalam hal ini Bipolar

In [6]:
# Training menggunakan Delta Rule dengan aktivasi bipolar
for _ in range(num_iterations):
    for i in range(X.shape[0]):
        input_vector = X[i]
        target = t[i]

        # Hitung output
        y_in = np.dot(input_vector, W)

        # Hitung selisih (error)
        error = target - y_in
        # error = np.mean((target - y_in) ** 2)

        # Perbarui bobot dengan Delta Rule
        delta_W = learning_rate * np.outer(input_vector, error)
        W += delta_W

        # Print nilai error pada setiap iterasi
        print(error)

[-1.20023965  2.55914221]
[-1.56609048  0.84728877]
[-0.14489838 -1.78641349]
[-0.6486473 -2.2867851]
[-0.53665516  0.90867055]
[-0.86130293 -0.03064355]
[-0.12947016 -0.62061978]
[-0.47062538 -1.06621299]
[-0.24385758  0.33808844]
[-0.49390428 -0.21012777]
[-0.08233787 -0.20115483]
[-0.31467917 -0.53187914]
[-0.11046953  0.13850279]
[-0.29071623 -0.19400819]
[-0.04461014 -0.0531187 ]
[-0.20197938 -0.28080319]
[-0.04853435  0.06574267]
[-0.1736449  -0.14017719]
[-0.02109919 -0.00374602]
[-0.12667466 -0.15458417]
[-0.01972656  0.03656421]
[-0.10446146 -0.09216836]
[-0.00821687  0.01023555]
[-0.07830673 -0.08748477]
[-0.00660499  0.02287524]
[-0.06299926 -0.05782895]
[-0.00186863  0.01207249]
[-0.04793131 -0.05033031]
[-0.00094941  0.01522487]
[-0.0379834  -0.03532785]
[0.00086841 0.01024399]
[-0.02912235 -0.02920201]
[0.00120257 0.01036009]
[-0.02285687 -0.02121993]
[0.00177414 0.00774281]
[-0.01758772 -0.01699775]
[0.00177537 0.00706049]
[-0.01371437 -0.01259549]
[0.00183916 0.00552614

### Testing

Acuan:

<img src="./image/problem.png" alt="image" width="400" height="150">

#### Testing menggunakan 1 data

In [7]:
# Uji dengan data input tertentu
input_vector = np.array([1, 1, 1, 1])
output = ham_bipolar(input_vector, W)

print("Input Vector:", input_vector)
print("Output:", output)

Input Vector: [1 1 1 1]
Output: [ 1 -1]


#### Testing menggunakan beberapa data

Pada testing kedua menggunakan beberapa data, saya mencoba untuk mengacak input yang sudah diberikan pada tabel sebelumnya. Tetunya target juga disesuaikan dengan inputan.

In [8]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

# Data sebenarnya (actual)
actual_data = np.array([[-1, 1],
                        [1, -1],
                        [-1, 1],
                        [1, -1]])


# Vektor input untuk pengujian
test_inputs = np.array([[-1, -1, -1, 1],
                        [1, 1, -1, 1],
                        [-1, -1, 1, 1],
                        [1, 1, 1, 1]])

print("Data input:\n",test_inputs)

# Data prediksi
predicted_data = np.array([ham_bipolar(input_vector, W) for input_vector in test_inputs])

print("\nPredicted Data:")
print(predicted_data)

# Menghitung confusion matrix dengan scikit-learn
confusion_matrix_result = confusion_matrix(actual_data.flatten(), predicted_data.flatten())

print("\nConfusion Matrix:")
print(confusion_matrix_result)

# Print the classification report
print("\nClassification Report:\n")

report = classification_report(actual_data.flatten(), predicted_data.flatten())
print(report)

Data input:
 [[-1 -1 -1  1]
 [ 1  1 -1  1]
 [-1 -1  1  1]
 [ 1  1  1  1]]

Predicted Data:
[[-1  1]
 [ 1 -1]
 [-1  1]
 [ 1 -1]]

Confusion Matrix:
[[4 0]
 [0 4]]

Classification Report:

              precision    recall  f1-score   support

          -1       1.00      1.00      1.00         4
           1       1.00      1.00      1.00         4

    accuracy                           1.00         8
   macro avg       1.00      1.00      1.00         8
weighted avg       1.00      1.00      1.00         8



In [9]:
mse = np.mean((predicted_data - actual_data) ** 2)

print("Mean Squared Error (MSE):", mse)

Mean Squared Error (MSE): 0.0
